// Generated by ReScript, PLEASE EDIT WITH CARE


var Scripts = {};

var Links = {};

var LiveReload = {};

var Meta = {};

var Outlet = {};

var $$Headers = {};

var Loader = {};

function MakeLoader(Data) {
  return {};
}

function MakeAction(Data) {
  return {};
}

export {
  Scripts ,
  Links ,
  LiveReload ,
  Meta ,
  Outlet ,
  $$Headers ,
  Loader ,
  MakeLoader ,
  MakeAction ,
}
/* No side effect */
